### ISSUE TITLE
Add flea deployment and service to helm chart

### ISSUE THREAD

**Issue by nkashy1** [doc-ai/tensorio-models#102]
There is currently now way to release flea via helm. This needs to be fixed.

**Comment by nkashy1** [comment]
The current `values.yaml` structure is as follows:
```
namespace: default

deployment:
  replicas: 1
  repository: docai/tensorio-models
  tag: latest
  pullPolicy: Always
  backend: memory

service:
  type: ClusterIP
  grpcPort: 7316
  restPort: 7317
  hostname: tensorio-models.default
```

Here, `deployment` and `service` pertain to a `tensorio-models` repository deployment.

The extension I propose is to add one layer of keys on top of the existing `values.yaml` structure so that it will look like:
```
repository:
  namespace: default
  deployment:
    ...
  service:
    ...
flea:
  namespace: default
  deployment:
    ...
  service:
    ...
```

Flea helm templates will be deployed conditionally on there being a `flea` key in the `values.yaml` -- I will have to look up how to do that, but it should not be too difficult. Worst case, we will require an explicit `release` subkey under `flea` which can bet set to `true` or `false` depending on whether or not `flea` should be deployed as part of that release.
